---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-issuer
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflare-issuer-secret
  data:
  - secretKey: CLOUDFLARE_API_TOKEN
    remoteRef:
      key: cert-manager
      property: cloudflare-api-token
