---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubernetes-sigs-node-feature-discovery-charts
spec:
  interval: 1h
  url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
  timeout: 3m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app node-feature-discovery
spec:
  interval: 1h
  chart:
    spec:
      chart: *app
      version: 0.17.3
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-node-feature-discovery-charts
      interval: 1h
  maxHistory: 2
  install:
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    master:
      replicaCount: 2

    worker:
      config:
        core:
          sources:
            - pci
            - system
            - usb

    prometheus:
      enable: true
      scrapeInterval: 60s
