---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: branding
  labels:
    dns.homelab/external: "true"
spec:
  endpoints:
  - dnsName: "branding.${DOMAIN_8}"
    recordTTL: 60
    recordType: CNAME
    targets:
    - "external.${DOMAIN_8}"
