---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mariadb-operator
spec:
  interval: 30m
  url: https://helm.mariadb.com/mariadb-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator-crds
spec:
  interval: 30m
  chart:
    spec:
      chart: mariadb-operator-crds
      version: 25.10.1
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
      interval: 30m
