---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: unbound-postgres
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: unbound-xi-game
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:${POSTGRESQL_VERSION}
  primaryUpdateStrategy: unsupervised
  enablePDB: true
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required
    topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - w01
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                  - workers
  minSyncReplicas: 1
  maxSyncReplicas: 1
  storage:
    size: 100Gi
    storageClass: openebs-hostpath
  superuserSecret:
    name: unbound-postgres-superuser
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: unbound
      owner: unbound_migrator
      secret:
        name: unbound-postgres-migrator
      dataChecksums: true
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
  postgresql:
    shared_preload_libraries:
      - pg_stat_statements
    parameters:
      max_connections: "100"
      shared_buffers: 2GB
      effective_cache_size: 6GB
      work_mem: 16MB
      maintenance_work_mem: 512MB
      checkpoint_timeout: 15min
      checkpoint_completion_target: "0.9"
      min_wal_size: 1GB
      max_wal_size: 4GB
      wal_compression: lz4
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      maintenance_io_concurrency: "100"
      autovacuum_max_workers: "5"
      autovacuum_naptime: 30s
      autovacuum_vacuum_cost_limit: "2000"
      default_statistics_target: "200"
      jit: "off"
      track_io_timing: "on"
      log_min_duration_statement: "500"
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
  resources:
    requests:
      cpu: 2
      memory: 4Gi
    limits:
      memory: 8Gi
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: unbound-postgres-r2
        serverName: unbound-postgres-v1
