---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: unbound-postgres-r2
spec:
  configuration:
    data:
      compression: lz4
    destinationPath: s3://${R2_BUCKET_NAME}/
    endpointURL: https://d09aa6ad2c849681b113b8dbb5cd3820.r2.cloudflarestorage.com
    s3Credentials:
      accessKeyId:
        name: unbound-postgres-r2
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: unbound-postgres-r2
        key: AWS_SECRET_ACCESS_KEY
    wal:
      compression: lz4
      maxParallel: 8
  retentionPolicy: 30d
