apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-tcp-configmap
data:
  # origin configuration: https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/configure-tunnels/cloudflared-parameters/origin-parameters/
  # config file docs: https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/do-more-with-tunnels/local-management/configuration-file/
  config.yaml: |
    tunnel: "${TUNNEL_ID}"
    no-autoupdate: true

    ingress:

      - service: "tcp://login-server.go-ffxi.svc.cluster.local:54231"
