---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
components:
  - ../../components/common
resources:
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./spegel/ks.yaml
  - ./metrics-server/ks.yaml
  - ./reflector/ks.yaml
  - ./reloader/ks.yaml
  - ./descheduler/ks.yaml
  - ./generic-device-plugin/ks.yaml
  - ./node-feature-discovery/ks.yaml
  - ./intel-device-plugin/ks.yaml
  # - ./amd-device-plugin/ks.yaml
