---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: game-server-connect
spec:
  commonName: calamityxi
  dnsNames:
    - "login.${DOMAIN_8}"
  duration: 2160h
  isCA: false
  issuerRef:
    name: calamityxi
    kind: Issuer
    group: cert-manager.io
  renewBefore: 360h
  secretName: game-server-connect-tls
  usages:
    - server auth
