---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: calamityxi-ghcr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: calamityxi-ghcr-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .DOCKER_CONFIG_JSON }}"
  dataFrom:
    - extract:
        key: github-pat-calamityxi-private-images
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: calamityxi-game-server-common-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: calamityxi-game-server-common-credentials-secret
    template:
      data:
        XI_NETWORK_SQL_HOST: "early-access-mariadb-internal"
        XI_NETWORK_SQL_PORT: "3306"
        XI_NETWORK_SQL_DATABASE: "early-access-mariadb"
        XI_NETWORK_SQL_LOGIN: "calamityxi-early-access"
        XI_NETWORK_SQL_PASSWORD: "{{ .USER_PASSWORD }}"
        MAP_HEARTBEAT_BEARER_TOKEN: "{{ .MAP_HEARTBEAT_BEARER_TOKEN }}"
        DOWNSTREAM_BEARER_TOKEN: "{{ .MAP_HEARTBEAT_BEARER_TOKEN }}"
  dataFrom:
    - extract:
        key: calamityxi-mariadb-early-access
    - extract:
        key: calamityxi-map-sidecar
