---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./grafanadashboard.yaml
  - ./issuer.yaml
  - ./certificate.yaml
  - ./helmrelease.yaml
  - ./operator-job-rbac.yaml
  - ./prometheusrule.yaml
  - ./servicemonitor.yaml

configMapGenerator:
  - name: grafana-dashboard-calamityxi-operator-overview
    files:
      - operator-overview.json=./resources/operator-overview.json

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/managed-by: grafana-operator
