---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: operator
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - calamityxi
  selector:
    matchLabels:
      app.kubernetes.io/component: manager
      app.kubernetes.io/instance: operator
      app.kubernetes.io/name: calamityxi-operator
