---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tracearr-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tracearr-postgres-secret
    template:
      data:
        POSTGRES_PASSWORD: '{{ .DB_PASSWORD }}'
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: tracearr
      property: DB_PASSWORD
