apiVersion: v1
kind: ConfigMap
metadata:
  name: calamityxi-upstream-game-server-hook-template
data:
  content: |
    spec:
      serviceAccountName: calamityxi-upstream-game-server-runners
      containers:
        - name: "$job"
          securityContext:
            runAsUser: 0
            runAsGroup: 0
