---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calamityxi-upstream-game-server-runners
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set
  values:
    githubConfigUrl: https://github.com/CalamityFFXI/upstream-game-server
    githubConfigSecret: calamityxi-upstream-game-server-runners-secret
    runnerScaleSetName: calamityxi-upstream-game-server-runners
    minRunners: 1
    maxRunners: 2

    containerMode:
      type: kubernetes
      kubernetesModeWorkVolumeClaim:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: openebs-hostpath

    controllerServiceAccount:
      name: actions-runner-controller
      namespace: actions-runner-system

    template:
      spec:
        initContainers:
          - name: kube-init
            image: ghcr.io/home-operations/actions-runner:2.334.0@sha256:95d91d7f8d241e319ef2f4fec08f417aa1606b96fbb327643f75c303acd30002
            command:
              - sudo
              - chown
              - -R
              - 1001:123
              - /home/runner/_work
            volumeMounts:
              - name: work
                mountPath: /home/runner/_work

        containers:
          - name: runner
            image: ghcr.io/home-operations/actions-runner:2.334.0@sha256:95d91d7f8d241e319ef2f4fec08f417aa1606b96fbb327643f75c303acd30002
            command:
              - /home/runner/run.sh
            env:
              - name: ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE
                value: /home/runner/hook-template/content
              - name: NODE
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            volumeMounts:
              - name: hook-template
                mountPath: /home/runner/hook-template
                readOnly: true
        volumes:
          - name: hook-template
            configMap:
              name: calamityxi-upstream-game-server-hook-template

        serviceAccountName: calamityxi-upstream-game-server-runners
