---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: unbound-game-server
  labels:
    app.kubernetes.io/name: unbound-game-server
    app.kubernetes.io/part-of: unbound-xi-game
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: unbound-game-server
      app.kubernetes.io/component: public-zone
  podMetricsEndpoints:
    - port: management
      path: /metrics
      interval: 30s
      scrapeTimeout: 5s
