---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bug-bounty-release
data:
  # renovate-release: depName=git.r1p.dev/unbound-xi/bug-bounty-server
  BUG_BOUNTY_SERVER_VERSION: v0.1.3
  BUG_BOUNTY_SERVER_DIGEST: sha256:14bb11f4c2d180b044060c2084db9b44f442f60abd87f19522ccc853496181ff
  # renovate-release: depName=git.r1p.dev/unbound-xi/bug-bounty-website
  BUG_BOUNTY_WEBSITE_VERSION: v0.1.3
  BUG_BOUNTY_WEBSITE_DIGEST: sha256:c6bcf716dd57cd162867cd350e2425e783f138ee5093e8161e9782cfe2e58ca3
