---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
spec:
  route:
    groupBy:
      - alertname
      - cluster
      - job
    groupInterval: 5m
    groupWait: 1m
    receiver: "null"
    repeatInterval: 12h
    routes:
      - receiver: "null"
        matchers:
          - name: alertname
            value: InfoInhibitor
            matchType: =
      - receiver: discord-calamityxi-search-server
        matchers:
          - name: discord_channel
            value: calamityxi-search-server
            matchType: =
      - receiver: discord-calamityxi-world-server
        matchers:
          - name: discord_channel
            value: calamityxi-world-server
            matchType: =
      - receiver: discord-calamityxi-connect-server
        matchers:
          - name: discord_channel
            value: calamityxi-connect-server
            matchType: =
  inhibitRules:
    - equal:
        - alertname
        - namespace
      sourceMatch:
        - name: severity
          value: critical
          matchType: =
      targetMatch:
        - name: severity
          value: warning
          matchType: =
  receivers:
    - name: "null"
    - name: discord-calamityxi-search-server
      discordConfigs:
        - apiURL:
            name: alertmanager-discord-webhooks
            key: calamityxi-search-server
          sendResolved: true
    - name: discord-calamityxi-world-server
      discordConfigs:
        - apiURL:
            name: alertmanager-discord-webhooks
            key: calamityxi-world-server
          sendResolved: true
    - name: discord-calamityxi-connect-server
      discordConfigs:
        - apiURL:
            name: alertmanager-discord-webhooks
            key: calamityxi-connect-server
          sendResolved: true
