---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-discord-webhooks
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: alertmanager-discord-webhooks
  data:
    - secretKey: calamityxi-search-server
      remoteRef:
        key: alertmanager-discord-webhooks
        property: calamityxi-search-server
    - secretKey: calamityxi-world-server
      remoteRef:
        key: alertmanager-discord-webhooks
        property: calamityxi-world-server
    - secretKey: calamityxi-connect-server
      remoteRef:
        key: alertmanager-discord-webhooks
        property: calamityxi-connect-server
    - secretKey: calamityxi-operator
      remoteRef:
        key: alertmanager-discord-webhooks
        property: calamityxi-operator
