---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-discord-webhooks
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: alertmanager-discord-webhooks
  data:
    - secretKey: homelab-alerts
      remoteRef:
        key: alertmanager-discord-webhooks
        property: homelab-alerts
