---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kube-prometheus-stack-additional
spec:
  groups:
    - name: kube-prometheus-stack-additional.rules
      rules:
        - alert: DockerhubRateLimitRisk
          expr: |
            count(time() - container_last_seen{image=~"(docker.io).*",container!=""} < 30) > 100
          annotations:
            summary: >-
              Kubernetes cluster Dockerhub rate limit risk
          labels:
            severity: critical

        - alert: OomKilled
          expr: |
            (kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 10m >= 1) and ignoring (reason) min_over_time(kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}[10m]) == 1
          annotations:
            summary: >-
              Container {{ $labels.container }} in pod {{ $labels.namespace }}/{{ $labels.pod }} has been OOMKilled {{ $value }} times in the last 10 minutes.
          labels:
            severity: critical

        - alert: etcdDatabaseHighFragmentationRatio
          expr: |-
            (
              last_over_time(etcd_mvcc_db_total_size_in_use_in_bytes{job=~".*etcd.*"}[5m])
              /
              last_over_time(etcd_mvcc_db_total_size_in_bytes{job=~".*etcd.*"}[5m])
            ) < 0.5
            and
            (
              (
                last_over_time(etcd_mvcc_db_total_size_in_bytes{job=~".*etcd.*"}[5m])
                -
                last_over_time(etcd_mvcc_db_total_size_in_use_in_bytes{job=~".*etcd.*"}[5m])
              )
              /
              last_over_time(etcd_server_quota_backend_bytes{job=~".*etcd.*"}[5m])
            ) > 0.25
          for: 2h
          annotations:
            description: >-
              etcd cluster "{{ $labels.job }}": database size in use on instance
              {{ $labels.instance }} is {{ $value | humanizePercentage }} of
              the actual allocated disk space, and reclaimable fragmented space
              is more than 25% of the backend quota. Run defragmentation (e.g.
              etcdctl defrag) during a maintenance window to retrieve the
              unused fragmented disk space.
            runbook_url: https://etcd.io/docs/v3.5/op-guide/maintenance/#defragmentation
            summary: etcd database fragmentation is wasting significant quota.
          labels:
            severity: warning

        - alert: KubeDeploymentReplicasMismatch
          expr: |-
            (
              (
                kube_deployment_spec_replicas{job="kube-state-metrics", namespace!="calamityxi"}
                or
                kube_deployment_spec_replicas{job="kube-state-metrics", namespace="calamityxi", deployment!~"cxi-world($|-.*)"}
              )
                >
              (
                kube_deployment_status_replicas_available{job="kube-state-metrics", namespace!="calamityxi"}
                or
                kube_deployment_status_replicas_available{job="kube-state-metrics", namespace="calamityxi", deployment!~"cxi-world($|-.*)"}
              )
            ) and (
              (
                changes(kube_deployment_status_replicas_updated{job="kube-state-metrics", namespace!="calamityxi"}[10m])
                ==
                0
              )
              or
              (
                changes(kube_deployment_status_replicas_updated{job="kube-state-metrics", namespace="calamityxi", deployment!~"cxi-world($|-.*)"}[10m])
                ==
                0
              )
            )
          for: 15m
          annotations:
            description: >-
              Deployment {{ $labels.namespace }}/{{ $labels.deployment }} has
              not matched the expected number of replicas for longer than 15
              minutes on cluster {{ $labels.cluster }}.
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubedeploymentreplicasmismatch
            summary: Deployment has not matched the expected number of replicas.
          labels:
            severity: warning

        - alert: KubeDeploymentRolloutStuck
          expr: |-
            (
              kube_deployment_status_condition{condition="Progressing", status="false", job="kube-state-metrics", namespace!="calamityxi"}
              != 0
            )
            or
            (
              kube_deployment_status_condition{condition="Progressing", status="false", job="kube-state-metrics", namespace="calamityxi", deployment!~"cxi-world($|-.*)"}
              != 0
            )
          for: 15m
          annotations:
            description: >-
              Rollout of deployment {{ $labels.namespace }}/{{ $labels.deployment }}
              is not progressing for longer than 15 minutes on cluster
              {{ $labels.cluster }}.
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubedeploymentrolloutstuck
            summary: Deployment rollout is not progressing.
          labels:
            severity: warning

        - alert: KubePodNotReady
          expr: |-
            sum by (namespace, pod, job, cluster) (
              max by (namespace, pod, job, cluster) (
                kube_pod_status_phase{job="kube-state-metrics", pod!~"cxi-world-.*", namespace=~".*", phase=~"Pending|Unknown"}
                or
                (
                  kube_pod_status_phase{job="kube-state-metrics", pod!~"cxi-world-.*", namespace=~".*", phase="Running"} == 1
                  and on (namespace, pod, cluster)
                  kube_pod_status_ready{job="kube-state-metrics", pod!~"cxi-world-.*", namespace=~".*", condition="true"} == 0
                )
              ) * on (namespace, pod, cluster) group_left() topk by (namespace, pod, cluster) (
                1, max by (namespace, pod, owner_kind, cluster) (kube_pod_owner{owner_kind!="Job"})
              )
            ) > 0
          for: 15m
          annotations:
            description: >-
              Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-ready
              state for longer than 15 minutes on cluster {{ $labels.cluster }}.
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubepodnotready
            summary: Pod has been in a non-ready state for more than 15 minutes.
          labels:
            severity: warning
