---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kube-prometheus-stack-additional
spec:
  groups:
    - name: kube-prometheus-stack-additional.rules
      rules:
        - alert: DockerhubRateLimitRisk
          expr: |
            count(time() - container_last_seen{image=~"(docker.io).*",container!=""} < 30) > 100
          annotations:
            summary: >-
              Kubernetes cluster Dockerhub rate limit risk
          labels:
            severity: critical

        - alert: OomKilled
          expr: |
            (kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 10m >= 1) and ignoring (reason) min_over_time(kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}[10m]) == 1
          annotations:
            summary: >-
              Container {{ $labels.container }} in pod {{ $labels.namespace }}/{{ $labels.pod }} has been OOMKilled {{ $value }} times in the last 10 minutes.
          labels:
            severity: critical

        - alert: KubeDeploymentReplicasMismatch
          expr: |-
            (
              (
                kube_deployment_spec_replicas{job="kube-state-metrics", namespace!="calamityxi"}
                or
                kube_deployment_spec_replicas{job="kube-state-metrics", namespace="calamityxi", deployment!="cxi-world"}
              )
                >
              (
                kube_deployment_status_replicas_available{job="kube-state-metrics", namespace!="calamityxi"}
                or
                kube_deployment_status_replicas_available{job="kube-state-metrics", namespace="calamityxi", deployment!="cxi-world"}
              )
            ) and (
              (
                changes(kube_deployment_status_replicas_updated{job="kube-state-metrics", namespace!="calamityxi"}[10m])
                ==
                0
              )
              or
              (
                changes(kube_deployment_status_replicas_updated{job="kube-state-metrics", namespace="calamityxi", deployment!="cxi-world"}[10m])
                ==
                0
              )
            )
          for: 15m
          annotations:
            description: >-
              Deployment {{ $labels.namespace }}/{{ $labels.deployment }} has
              not matched the expected number of replicas for longer than 15
              minutes on cluster {{ $labels.cluster }}.
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubedeploymentreplicasmismatch
            summary: Deployment has not matched the expected number of replicas.
          labels:
            severity: warning

        - alert: KubeDeploymentRolloutStuck
          expr: |-
            (
              kube_deployment_status_condition{condition="Progressing", status="false", job="kube-state-metrics", namespace!="calamityxi"}
              != 0
            )
            or
            (
              kube_deployment_status_condition{condition="Progressing", status="false", job="kube-state-metrics", namespace="calamityxi", deployment!="cxi-world"}
              != 0
            )
          for: 15m
          annotations:
            description: >-
              Rollout of deployment {{ $labels.namespace }}/{{ $labels.deployment }}
              is not progressing for longer than 15 minutes on cluster
              {{ $labels.cluster }}.
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubedeploymentrolloutstuck
            summary: Deployment rollout is not progressing.
          labels:
            severity: warning
