---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: uxi-ptr-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: uxi-ptr-postgres-secret
    template:
      data:
        username: "{{ .POSTGRES_SUPER_USER }}"
        password: "{{ .POSTGRES_SUPER_PASS }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
      metadata:
        labels:
          cnpg.io/reload: "true"
  dataFrom:
    - extract:
        key: uxi-ptr-postgres
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: uxi-ptr-postgres-app
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: uxi-ptr-postgres-app-secret
    template:
      data:
        username: uxi_ptr
        password: "{{ .UXI_PTR_POSTGRES_PASS }}"
  dataFrom:
    - extract:
        key: uxi-ptr-postgres
