---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wyoming-piper
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    strategy:
      name: RetryOnFailure
  upgrade:
    strategy:
      name: RetryOnFailure
  values:
    controllers:
      wyoming-piper:
        containers:
          app:
            image:
              repository: rhasspy/wyoming-piper
              tag: 1.6.3
            args:
              - --voice
              - en_US-ryan-high
            env:
              TZ: America/New_York

    defaultPodOptions:
      hostUsers: false

    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: "10.50.100.3"
        ports:
          whisper:
            port: 10200

    persistence:
      data:
        existingClaim: "{{ .Release.Name }}-cache"
