---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app wyoming-piper
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      wyoming-piper:
        containers:
          app:
            image:
              repository: rhasspy/wyoming-piper
              tag: 1.6.2
            args:
              - --voice
              - en_GB-alan-medium
            env:
              TZ: America/New_York
    service:
      app:
        ports:
          whisper:
            port: 10200
    persistence:
      data:
        existingClaim: *app
