---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app temporal
  namespace: &namespace temporal
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: onepassword-stores
      namespace: external-secrets
    - name: database
      namespace: *namespace
  interval: 1h
  path: ./kubernetes/apps/temporal/temporal/app
  postBuild:
    substituteFrom:
      - kind: Secret
        name: domains-secret
        optional: false
    substitute:
      APP: *app
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
