---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: buzz
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: buzz-secret
    template:
      data:
        BUZZ_RELAY_PRIVATE_KEY: "{{ .BUZZ_RELAY_PRIVATE_KEY }}"
        BUZZ_GIT_HOOK_HMAC_SECRET: "{{ .BUZZ_GIT_HOOK_HMAC_SECRET }}"
        BUZZ_OWNER_PUBKEY: "{{ .BUZZ_OWNER_PUBKEY }}"
        BUZZ_S3_ACCESS_KEY: "{{ .BUZZ_R2_ACCESS_KEY_ID }}"
        BUZZ_S3_SECRET_KEY: "{{ .BUZZ_R2_SECRET_ACCESS_KEY }}"
        REDIS_URL: "redis://buzz-redis.ai.svc.cluster.local:6379"
        DATABASE_URL: "postgresql://{{ .BUZZ_POSTGRES_USER }}:{{ .BUZZ_POSTGRES_PASS }}@postgres-rw.databases.svc.cluster.local:5432/buzz"
        INIT_POSTGRES_DBNAME: buzz
        INIT_POSTGRES_HOST: postgres-rw.databases.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .BUZZ_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .BUZZ_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: buzz
    - extract:
        key: cloudnative-pg
