---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app rdt-client
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      app:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/rogerfar/rdtclient
              tag: 2.0.113@sha256:c457124e30d2800c81a5ff7b491c9f10fc7c4efa5dbf74fd002648bb36b628f8
            env:
              TZ: America/New_York
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /login
                    port: &port 6500
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 100m
    defaultPodOptions:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      hostname: rdt
    persistence:
      data:
        existingClaim: *app
      media:
        type: nfs
        server: synology.batcave
        path: /volume1/batcave-media/downloads
        globalMounts:
          - path: /data/downloads
    route:
      app:
        hostnames:
          - "rdt.${DOMAIN_5}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: domain-5-subdomain-https
    service:
      app:
        ports:
          http:
            port: *port
