---
version: "3"

set:
  - pipefail
shopt:
  - globstar

vars:
  KUBERNETES_DIR: "{{ .ROOT_DIR }}/kubernetes"
  TALOS_DIR: "{{ .ROOT_DIR }}/talos"
  BOOTSTRAP_DIR: "{{ .ROOT_DIR }}/bootstrap"

env:
  TALOSCONFIG: "{{ .TALOS_DIR }}/talosconfig"

includes:
  bootstrap: .taskfiles/bootstrap
  talos: .taskfiles/talos
  volsync: .taskfiles/volsync

tasks:
  default:
    cmd: task --list
    silent: true

  k9s:
    desc: Run k9s
    cmd: k9s
    env:
      KUBECONFIG: "{{ .KUBERNETES_DIR }}/kubeconfig"
    preconditions:
      - which k9s
