---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: uxi-ptr
components:
  - ../../../components/common
resources:
  - ./postgres/ks.yaml
  - ./api/ks.yaml
  - ./state/ks.yaml
  - ./social/ks.yaml
  - ./gateway/ks.yaml
  - ./map-worker/ks.yaml
patches:
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: not-used
        labels:
          uxi.homelab/nats-access: "true"
    target:
      kind: Namespace
      name: not-used
