---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: branding-ghcr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: branding-ghcr-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .DOCKER_CONFIG_JSON }}"
  dataFrom:
    - extract:
        key: calamityxi-branding
