---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: temporal
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: temporal-secret
    template:
      data:
        DBNAME: temporal
        DB_PORT: "5432"
        POSTGRES_SEEDS: postgres-rw
        POSTGRES_USER: "{{ .POSTGRES_SUPER_USER }}"
        POSTGRES_PWD: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: temporal
