---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: temporal
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      server:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: temporalio/auto-setup
              tag: 1.28.0.0@sha256:3ee84bf3ec5494f2be6ee0c1fea3b52684e50da3ddc5f997e6fa56ad340da9a8
            env:
              DB: postgres12
              DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/dev-dynamic-config.yaml
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"

      ui:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: temporalio/ui
              tag: 2.39.0@sha256:b768f87f18b59663a6749e98a2f7782c266e8e4e4749f92248e2ba41d6330d3f
            env:
              TEMPORAL_ADDRESS: &temporalAddress temporal-server:7233
              TEMPORAL_CORS_ORIGINS: http://localhost:3000

      admin-tools:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: temporalio/admin-tools
              tag: 1.28@sha256:45bf84a03c978329639bea5722438b7dcda1559c06ef237e6a288662bb2fe603
            env:
              TEMPORAL_ADDRESS: *temporalAddress

    service:
      server:
        primary: true
        controller: server
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.50.100.4
        ports:
          http:
            port: 7233
      ui:
        controller: ui
        ports:
          http:
            port: &uiHttpPort 8080

    route:
      ui:
        hostnames:
          - "{{ .Release.Name }}.${DOMAIN_5}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: domain-5-subdomain-https
        rules:
          - backendRefs:
              - identifier: ui
                port: *uiHttpPort

    persistence:
      dynamic-config:
        type: configMap
        name: "{{ .Release.Name }}-configmap"
        advancedMounts:
          server:
            app:
            - path: /etc/temporal/config/dynamicconfig
