---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: temporal
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      server:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: temporalio/auto-setup
              tag: 1.28.1.0@sha256:607d68caa111338d754771efb876c92dfcdae06d056e4530bb31cd0f37406e6a
            env:
              DB: postgres12
              DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/dev-dynamic-config.yaml
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"

      ui:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: temporalio/ui
              tag: 2.40.1@sha256:afc274fbc21e217ff4585394b604aa2f97fac71059bf301d9e70269bd164bd3a
            env:
              TEMPORAL_ADDRESS: &temporalAddress temporal-server:7233
              TEMPORAL_CORS_ORIGINS: http://localhost:3000

      admin-tools:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: temporalio/admin-tools
              tag: 1.28@sha256:01537b62d995f27a0f0d33a01ac4caa6779622f454fb2eb36fed0dccd45c6244
            env:
              TEMPORAL_ADDRESS: *temporalAddress

    service:
      server:
        primary: true
        controller: server
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.50.100.4
        ports:
          http:
            port: 7233
      ui:
        controller: ui
        ports:
          http:
            port: &uiHttpPort 8080

    defaultPodOptions:
      hostUsers: false

    route:
      ui:
        hostnames:
          - "{{ .Release.Name }}.${DOMAIN_5}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: domain-5-subdomain-https
        rules:
          - backendRefs:
              - identifier: ui
                port: *uiHttpPort

    persistence:
      dynamic-config:
        type: configMap
        name: "{{ .Release.Name }}-configmap"
        advancedMounts:
          server:
            app:
            - path: /etc/temporal/config/dynamicconfig
