---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: temporal
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      server:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: temporalio/auto-setup
              tag: 1.29.4.1@sha256:69e19e8aae1c1362f9fda86ad98624e8495b0330e4674c693a931b1f8ad9bce8
            env:
              DB: postgres12
              DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/dev-dynamic-config.yaml
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"

      ui:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: temporalio/ui
              tag: 2.48.3@sha256:e5523746f54a8b908b0be69f6274ca1abf2aa0a51714a85b6a4641310ff60286
            env:
              TEMPORAL_ADDRESS: &temporalAddress temporal-server:7233
              TEMPORAL_CORS_ORIGINS: http://localhost:3000

      admin-tools:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: temporalio/admin-tools
              tag: 1.30@sha256:9ac15d500f4020f7cc694ecc17085dfcfc2d4b1d0d2020dbe83b6f3d49e156e0
            env:
              TEMPORAL_ADDRESS: *temporalAddress

    service:
      server:
        primary: true
        controller: server
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.50.100.4
        ports:
          http:
            port: 7233
      ui:
        controller: ui
        ports:
          http:
            port: &uiHttpPort 8080

    defaultPodOptions:
      hostUsers: false

    route:
      ui:
        hostnames:
          - "{{ .Release.Name }}.${DOMAIN_5}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: domain-5-subdomain-https
        rules:
          - backendRefs:
              - identifier: ui
                port: *uiHttpPort

    persistence:
      dynamic-config:
        type: configMap
        name: "{{ .Release.Name }}-configmap"
        advancedMounts:
          server:
            app:
            - path: /etc/temporal/config/dynamicconfig
