---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
  labels:
    cnpg.io/reload: "true"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudnative-pg-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: &secretKey cloudnative-pg
        property: super-user
    - secretKey: password
      remoteRef:
        key: *secretKey
        property: super-pass
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: *secretKey
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: *secretKey
        property: AWS_SECRET_ACCESS_KEY
