---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: openwebui-secret
    template:
      data:
        DB_TYPE: postgresdb
        DB_POSTGRESDB_DATABASE: &dbName openwebui
        DB_POSTGRESDB_HOST: &dbHost postgres-rw.databases.svc.cluster.local
        DB_POSTGRESDB_USER: &dbUser "{{ .OPENWEBUI_POSTGRES_USER }}"
        DB_POSTGRESDB_PASSWORD: &dbPass "{{ .OPENWEBUI_POSTGRES_PASS }}"
        DB_POSTGRESDB_PORT: "5432"
        DATABASE_URL: "postgresql://{{ .OPENWEBUI_POSTGRES_USER }}:{{ .OPENWEBUI_POSTGRES_PASS }}@postgres-rw.databases.svc.cluster.local:5432/openwebui?sslmode=disable"
        WEBUI_SECRET_KEY: "{{ .OPENWEBUI_WEBUI_SECRET_KEY }}"
        OLLAMA_BASE_URL: "{{ .OLLAMA_BASE_URL }}"
        # Postgres init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: '{{ .POSTGRES_SUPER_PASS }}'
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: openwebui
