---
apiVersion: v1
kind: ConfigMap
metadata:
  name: uxi-ptr-worker-config
data:
  config.toml: |
    [common]
    dev_mode = false
    content_dir = "/content"

    [worker]
    id = 1
    claims_all = true
    health_listen = "0.0.0.0:21019"
    api_internal_addr = "uxi-ptr-api-internal:21017"

    [bus]
    url = "nats://nats.uxi-nats.svc.cluster.local:4222"
    environment = "ptr"
    username = "ptr"
    password_file = "/secrets/nats/password"
