---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: frigate-secret
    creationPolicy: Owner
    template:
      data:
        PLUS_API_KEY: "{{ .PLUS_API_KEY }}"
  dataFrom:
    - extract:
        key: frigate
