---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wyoming-whisper-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
