---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    strategy:
      name: RetryOnFailure
  upgrade:
    strategy:
      name: RetryOnFailure
  values:
    controllers:
      sabnzbd:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/sabnzbd
              tag: 4.5.3@sha256:ecb57bd6257fbfbd9aee70d8ef3df8814b7270ae793fd1f44219ae73cacd519a
            env:
              SABNZBD__PORT: &port 8080
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                {{ .Release.Name }},
                {{ .Release.Name }}.{{ .Release.Namespace }},
                {{ .Release.Name }}.{{ .Release.Namespace }}.svc,
                {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster,
                {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local,
                {{ .Release.Name }}.${DOMAIN_5}
              TZ: America/New_York
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api?mode=version
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 100m
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 65536

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      incomplete:
        type: custom
        volumeSpec:
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Mi # Ignored
                storageClassName: openebs-hostpath
                volumeMode: Filesystem
      media:
        type: nfs
        server: nas.batcave
        path: /mnt/zpool/media/downloads
        globalMounts:
          - path: /data/downloads
      tmp:
        type: emptyDir

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${DOMAIN_5}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: domain-5-subdomain-https

    service:
      app:
        ports:
          http:
            port: *port
