---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: zooz-700-series-zwave-plus-s2
spec:
  rules:
  - # Zooz 700 Series Z-Wave Plus S2 Stick
    name: zwave
    labels:
      feature.node.kubernetes.io/zwave: "true"
    matchFeatures:
    - feature: usb.device
      matchExpressions:
        vendor:
          op: In
          value:
            - "0658"
        device:
          op: In
          value:
            - "0200"
