apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-configmap
data:
  # origin configuration: https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/configure-tunnels/cloudflared-parameters/origin-parameters/
  # config file docs: https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/do-more-with-tunnels/local-management/configuration-file/
  config.yaml: |
    tunnel: "${TUNNEL_ID}"
    no-autoupdate: true

    ingress:

      - hostname: "plex.${DOMAIN_5}"
        service: "${PLEX_PROXY_ADDRESS}"
        originRequest:
          originServerName: "external.${DOMAIN_5}"

      - hostname: "${DOMAIN_1}"
        service: &service https://cilium-gateway-external.kube-system.svc.cluster.local
        originRequest:
          originServerName: "external.${DOMAIN_1}"

      - hostname: "*.${DOMAIN_1}"
        service: *service
        originRequest:
          originServerName: "external.${DOMAIN_1}"

      - hostname: "${DOMAIN_2}"
        service: *service
        originRequest:
          originServerName: "external.${DOMAIN_2}"

      - hostname: "*.${DOMAIN_2}"
        service: *service
        originRequest:
          originServerName: "external.${DOMAIN_2}"

      - hostname: "${DOMAIN_3}"
        service: *service
        originRequest:
          originServerName: "external.${DOMAIN_3}"

      - hostname: "*.${DOMAIN_3}"
        service: *service
        originRequest:
          originServerName: "external.${DOMAIN_3}"

      - hostname: "${DOMAIN_4}"
        service: *service
        originRequest:
          originServerName: "external.${DOMAIN_4}"

      - hostname: "*.${DOMAIN_4}"
        service: *service
        originRequest:
          originServerName: "external.${DOMAIN_4}"

      - hostname: "${DOMAIN_5}"
        service: *service
        originRequest:
          originServerName: "external.${DOMAIN_5}"

      - hostname: "*.${DOMAIN_5}"
        service: *service
        originRequest:
          originServerName: "external.${DOMAIN_5}"

      - hostname: "${DOMAIN_6}"
        service: *service
        originRequest:
          originServerName: "external.${DOMAIN_6}"

      - hostname: "*.${DOMAIN_6}"
        service: *service
        originRequest:
          originServerName: "external.${DOMAIN_6}"

      - hostname: "${DOMAIN_7}"
        service: *service
        originRequest:
          originServerName: "external.${DOMAIN_7}"

      - hostname: "*.${DOMAIN_7}"
        service: *service
        originRequest:
          originServerName: "external.${DOMAIN_7}"

      - service: http_status:404
