---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crawl4ai
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    strategy:
      name: RetryOnFailure
  upgrade:
    strategy:
      name: RetryOnFailure
  values:
    controllers:
      crawl4ai:
        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            runAsNonRoot: true
            fsGroup: 999
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: unclecode/crawl4ai
              tag: 0.6.0-r2
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &httpPort 11235
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      crawl4ai:
        ports:
          http:
            port: *httpPort

    persistence:
      cache:
        type: emptyDir
        medium: Memory
        sizeLimit: 1Gi
        globalMounts:
        - path: /dev/shm
      data:
        existingClaim: "{{ .Release.Name }}-data"
        globalMounts:
          - path: /home/appuser
      tmpfs:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /tmp
