---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: calamityxi-ghcr
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: calamityxi-ghcr-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .DOCKER_CONFIG_JSON }}"
  dataFrom:
    - extract:
        key: github-pat-calamityxi-private-images
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: calamityxi
  namespace: flux-system
spec:
  interval: 30m
  url: oci://ghcr.io/calamityffxi/charts/calamityxi-operator
  secretRef:
    name: calamityxi-ghcr-secret
  ref:
    tag: 0.1.14
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
