---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: konflate
  labels:
    dns.homelab/external: "true"
spec:
  endpoints:
    - dnsName: konflate.${DOMAIN_7}
      recordTTL: 60
      recordType: CNAME
      targets:
        - external.${DOMAIN_7}
