---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: umami
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: umami-secret
    template:
      data:
        DATABASE_URL: "postgresql://{{ .UMAMI_POSTGRES_USER }}:{{ .UMAMI_POSTGRES_PASS }}@postgres-rw.databases.svc.cluster.local:5432/umami?sslmode=disable"
        APP_SECRET: "{{ .UMAMI_APP_SECRET }}"
        DISABLE_TELEMETRY: "1"
        INIT_POSTGRES_DBNAME: umami
        INIT_POSTGRES_HOST: postgres-rw.databases.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .UMAMI_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .UMAMI_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: umami
