---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflared-secret
    template:
      data:
        TUNNEL_TOKEN: |-
          {{ toJson (dict "a" .CLOUDFLARE_ACCOUNT_ID "t" .CLOUDFLARE_TUNNEL_ID "s" .CLOUDFLARE_TUNNEL_SECRET) | b64enc }}
        TUNNEL_ID: "{{ .CLOUDFLARE_TUNNEL_ID }}"
        PLEX_PROXY_ADDRESS: "{{ .PLEX_PROXY_ADDRESS }}"
  dataFrom:
    - extract:
        key: cloudflared
