---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: uxi-ptr-gateway
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: uxi-ptr-server
      app.kubernetes.io/component: gateway
