---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app unbound-postgres-secrets
  namespace: &namespace unbound-xi-game
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
      app.kubernetes.io/part-of: unbound-xi-game
  dependsOn:
    - name: onepassword-store
      namespace: external-secrets
  healthCheckExprs:
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  interval: 1h
  path: ./kubernetes/apps/unbound-xi-game/postgres/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app unbound-postgres
  namespace: &namespace unbound-xi-game
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
      app.kubernetes.io/part-of: unbound-xi-game
  dependsOn:
    - name: unbound-postgres-secrets
      namespace: *namespace
    - name: cloudnative-pg
      namespace: databases
    - name: cloudnative-pg-barman-cloud
      namespace: databases
    - name: openebs
      namespace: openebs-system
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      inProgress: '!has(status.conditions) || status.conditions.filter(e, e.type == "Ready").all(e, e.status != "True")'
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
    - apiVersion: postgresql.cnpg.io/v1
      kind: DatabaseRole
      inProgress: '!has(status.applied) || !status.applied'
      current: has(status.applied) && status.applied
  interval: 1h
  path: ./kubernetes/apps/unbound-xi-game/postgres/cluster
  postBuild:
    substitute:
      # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgresql
      POSTGRESQL_VERSION: 17.10-minimal-trixie@sha256:b8aa2492786fde3b1c00c0c156093ef05ce03df1541aead9d9c7b6abe27128e3
    substituteFrom:
      - kind: Secret
        name: unbound-postgres-r2
        optional: false
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: true
