---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app bazarr
  namespace: &namespace media
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/kopiur
    - ../../../../components/kopiur-restore
  dependsOn:
    - name: cert-manager-secrets
      namespace: cert-manager
    - name: kopiur-repository
      namespace: kopiur-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: *namespace
  healthCheckExprs:
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: SnapshotPolicy
      inProgress: status.conditions.exists(e, e.type == 'Reconciling' && e.status == 'True')
      failed: status.conditions.exists(e, e.type == 'Ready' && e.status == 'False') || status.conditions.exists(e, e.type == 'Stalled' && e.status == 'True')
      current: status.conditions.exists(e, e.type == 'Ready' && e.status == 'True')
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: SnapshotSchedule
      inProgress: status.conditions.exists(e, e.type == 'Reconciling' && e.status == 'True')
      failed: status.conditions.exists(e, e.type == 'Ready' && e.status == 'False') || status.conditions.exists(e, e.type == 'Stalled' && e.status == 'True')
      current: status.conditions.exists(e, e.type == 'Ready' && e.status == 'True')
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Restore
      inProgress: status.conditions.exists(e, e.type == 'Reconciling' && e.status == 'True') || status.phase != 'Completed'
      failed: status.phase == 'Failed' || status.conditions.exists(e, e.type == 'Stalled' && e.status == 'True')
      current: status.phase == 'Completed' && status.conditions.exists(e, e.type == 'Ready' && e.status == 'True')
  interval: 1h
  path: ./kubernetes/apps/media/bazarr/app
  postBuild:
    substituteFrom:
      - kind: Secret
        name: domains-secret
        optional: false
    substitute:
      APP: *app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
