---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-cloudflare
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: external-dns-cloudflare-secret
  data:
  - secretKey: CLOUDFLARE_API_TOKEN
    remoteRef:
      key: external-dns
      property: cloudflare-api-token
