---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns-cloudflare
  namespace: network
spec:
  interval: 30m
  url: https://kubernetes-sigs.github.io/external-dns
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-cloudflare
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.16.0
      sourceRef:
        kind: HelmRepository
        name: external-dns-cloudflare
      interval: 30m
  install:
    crds: CreateReplace
    disableSchemaValidation: true # Ref: https://github.com/kubernetes-sigs/external-dns/issues/5206
  upgrade:
    crds: CreateReplace
    disableSchemaValidation: true # Ref: https://github.com/kubernetes-sigs/external-dns/issues/5206
  values:
    fullnameOverride: &name external-dns-cloudflare
    domainFilters:
      - "${DOMAIN_1}"
      - "${DOMAIN_2}"
      - "${DOMAIN_3}"
      - "${DOMAIN_4}"
      - "${DOMAIN_5}"
      - "${DOMAIN_6}"
      - "${DOMAIN_7}"
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-cloudflare-secret
            key: CLOUDFLARE_API_TOKEN
    extraArgs:
      - --cloudflare-dns-records-per-page=1000
      - --cloudflare-proxied
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --label-filter=dns.homelab.arpa/external=true
      - --gateway-name=external
    podAnnotations:
      secret.reloader.stakater.com/reload: external-dns-cloudflare-secret
    policy: sync
    provider:
      name: cloudflare
    resources:
      requests:
        cpu: 13m
        memory: 42M
      limits:
        memory: 42M
    serviceMonitor:
      enabled: true
    sources:
      - crd
    triggerLoopOnEvent: true
    txtOwnerId: k8s
    txtPrefix: k8s.

  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: *name
            patch: |
              - op: add
                path: /spec/template/spec/enableServiceLinks
                value: false
