---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: go2rtc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: go2rtc-secret
    creationPolicy: Owner
    template:
      data:
        go2rtc.yaml: |
          log:
            output: "stdout"

          streams:
            main: "{{ .DRIVEWAY_MAIN }}"
            sub: "{{ .DRIVEWAY_SUB }}"
  dataFrom:
    - extract:
        key: go2rtc
