---
apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: talos
spec:
  parallelism: 1
  policy:
    waitForVolumeDetach: true
  maintenance:
    windows:
      - start: "0 3 * * 1,5"
        duration: 3h
        timezone: America/New_York
  talos:
    # renovate: datasource=custom.talos-factory depName=siderolabs/talos
    version: v1.13.7
  healthChecks:
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      expr: status.ceph.health in ['HEALTH_OK']
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Snapshot
      expr: status.phase in ['Succeeded', 'Failed']
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Restore
      expr: status.phase in ['Completed', 'Failed']
