---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grafana-secret
    template:
      data:
        admin-user: "{{ .GRAFANA_ADMIN_USER }}"
        admin-password: "{{ .GRAFANA_ADMIN_PASS }}"
        oauth-client-id: "{{ .GRAFANA_AUTHENTIK_CLIENT_ID }}"
        oauth-client-secret: "{{ .GRAFANA_AUTHENTIK_CLIENT_SECRET }}"
        oauth-role-attribute-path: "{{ .GRAFANA_AUTHENTIK_ROLE_ATTRIBUTE_PATH }}"
        authz-config: "{{ .GRAFANA_AUTHZ_CONFIG }}"
        TESLAMATE_DATABASE_USER: "{{ .TESLAMATE_DATABASE_USER }}"
        TESLAMATE_DATABASE_PASSWORD: "{{ .TESLAMATE_DATABASE_PASSWORD }}"
  dataFrom:
    - extract:
        key: grafana
    - extract:
        key: teslamate
