---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-mediacovers
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block # todo: change this to openebs-hostpath when ms-a2s get here
