---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: zigbee2mqtt-secret
    creationPolicy: Owner
  data:
    - secretKey: ZIGBEE2MQTT_CONFIG_ADVANCED_CHANNEL
      remoteRef:
        key: zigbee2mqtt
        property: advanced-channel
    - secretKey: ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY
      remoteRef:
        key: zigbee2mqtt
        property: network-key
    - secretKey: ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID
      remoteRef:
        key: zigbee2mqtt
        property: ext-pan-id
    - secretKey: ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID
      remoteRef:
        key: zigbee2mqtt
        property: pan-id
    - secretKey: ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD
      remoteRef:
        key: vernemq
        property: mqtt-password
