---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homelab-runners
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homelab-runners-secret
    creationPolicy: Owner
  data:
    - secretKey: github_app_id
      remoteRef:
        key: &name actions-runner-system
        property: app-id
    - secretKey: github_app_installation_id
      remoteRef:
        key: *name
        property: installation-id
    - secretKey: github_app_private_key
      remoteRef:
        key: *name
        property: app-private-key.pem
