---
kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: devices
spec:
  module: icmp
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - adguard.batcave
        - dabeast.batcave
        - genmon.batcave
        - pikvm.batcave
        - synology.batcave
        - unifi.batcave
        - zigbee-controller.batcave
