---
kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: plex
spec:
  module: http_2xx
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - http://nas.batcave:32400/identity
