---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-issuer
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflare-issuer-secret
    creationPolicy: Owner
  data:
  - secretKey: api-token
    remoteRef:
      key: cloudflare
      property: api-token
  - secretKey: domain-1
    remoteRef:
      key: cloudflare
      property: domain-1
