---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-issuer-secret
              key: CLOUDFLARE_API_TOKEN
        selector:
          dnsZones:
            - "${DOMAIN_1}"
            - "*.${DOMAIN_1}"
            - "${DOMAIN_2}"
            - "*.${DOMAIN_2}"
            - "${DOMAIN_3}"
            - "*.${DOMAIN_3}"
            - "${DOMAIN_4}"
            - "*.${DOMAIN_4}"
            - "${DOMAIN_5}"
            - "*.${DOMAIN_5}"
            - "${DOMAIN_6}"
            - "*.${DOMAIN_6}"
            - "${DOMAIN_7}"
            - "*.${DOMAIN_7}"
