---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-issuer-secret
              key: api-token
        selector:
          dnsZones:
            - "${domain1}"
            - "*.${domain1}"
            - "${domain2}"
            - "*.${domain2}"
            - "${domain3}"
            - "*.${domain3}"
            - "${domain4}"
            - "*.${domain4}"
            - "${domain5}"
            - "*.${domain5}"
            - "${domain6}"
            - "*.${domain6}"
