---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: gatus
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  groups:
    - name: gatus.rules
      rules:
        - alert: GatusEndpointDown
          expr: |
            gatus_results_endpoint_success == 0
          for: 5m
          annotations:
            summary: >-
              The {{ $labels.name }} endpoint is down
          labels:
            severity: critical
