---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tuppr
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tuppr
      app.kubernetes.io/instance: tuppr
