---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: uxi-ptr-nats
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: uxi-ptr-nats
    template:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "^uxi-ptr$"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "^uxi-ptr$"
      data:
        NATS_URL: nats://nats.uxi-nats.svc.cluster.local:4222
        NATS_USERNAME: ptr
        NATS_PASSWORD: "{{ .NATS_PASSWORD }}"
        auth.conf: |-
          users: [{ user: "ptr", password: {{ .NATS_PASSWORD | toJson }} }]
  data:
    - secretKey: NATS_PASSWORD
      remoteRef:
        key: uxi-nats-ptr
        property: NATS_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: uxi-production-nats
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: uxi-production-nats
    template:
      metadata:
        annotations:
          # Enable reflection only after the production namespace is defined.
          reflector.v1.k8s.emberstack.com/reflection-allowed: "false"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "false"
      data:
        NATS_URL: nats://nats.uxi-nats.svc.cluster.local:4222
        NATS_USERNAME: production
        NATS_PASSWORD: "{{ .NATS_PASSWORD }}"
        auth.conf: |-
          users: [{ user: "production", password: {{ .NATS_PASSWORD | toJson }} }]
  data:
    - secretKey: NATS_PASSWORD
      remoteRef:
        key: uxi-nats-production
        property: NATS_PASSWORD
