---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cloudflared-secrets
  namespace: &namespace network
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: onepassword-store
      namespace: external-secrets
  interval: 1h
  path: ./kubernetes/apps/network/cloudflared/secrets
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cloudflared
  namespace: &namespace network
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: onepassword-store
      namespace: external-secrets
    - name: cert-manager-secrets
      namespace: cert-manager
    - name: reflector
      namespace: kube-system
    - name: cloudflared-secrets
      namespace: *namespace
  interval: 1h
  path: ./kubernetes/apps/network/cloudflared/app
  postBuild:
    substituteFrom:
      - kind: Secret
        name: domains-secret
        optional: false
      - kind: Secret
        name: cloudflared-secret
        optional: false
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
