---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kopiur
  namespace: &namespace kopiur-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: snapshot-controller
      namespace: snapshot-system
    - name: openebs
      namespace: openebs-system
    - name: kube-prometheus-stack
      namespace: observability
    - name: grafana-operator
      namespace: observability
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: *namespace
  interval: 1h
  path: ./kubernetes/apps/kopiur-system/kopiur/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kopiur-secrets
  namespace: &namespace kopiur-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: onepassword-store
      namespace: external-secrets
  healthCheckExprs:
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  interval: 1h
  path: ./kubernetes/apps/kopiur-system/kopiur/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kopiur-repository
  namespace: &namespace kopiur-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: kopiur
      namespace: *namespace
    - name: kopiur-secrets
      namespace: *namespace
  healthCheckExprs:
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: ClusterRepository
      inProgress: status.phase in ['Pending', 'Initializing'] || status.observedGeneration != metadata.generation
      failed: status.phase == 'Failed'
      current: status.phase == 'Ready' && status.observedGeneration == metadata.generation
  interval: 1h
  path: ./kubernetes/apps/kopiur-system/kopiur/repository
  postBuild:
    substituteFrom:
      - kind: Secret
        name: kopia-storage-secret
        optional: false
      - kind: Secret
        name: domains-secret
        optional: false
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: true
