---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qdrant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: qdrant-secret
    creationPolicy: Owner
    template:
      data:
        QDRANT__SERVICE__API_KEY: "{{ .QDRANT_API_KEY }}"
  dataFrom:
    - extract:
        key: qdrant
