---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qdrant
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      qdrant:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "6333"

        containers:
          app:
            image:
              repository: ghcr.io/qdrant/qdrant/qdrant
              tag: v1.15.5-unprivileged@sha256:b83a7f4f1f6bf089fd99efa3f205546971603e2e61b2716a253a7ce780ecfe5d
            env:
              QDRANT__SERVICE__HTTP_PORT: &httpPort 6333
              QDRANT__SERVICE__GRPC_PORT: &grpcPort 6334
              QDRANT__SERVICE__ENABLE_CORS: "false"
              QDRANT__STORAGE__STORAGE_PATH: "/qdrant/storage"
              QDRANT__STORAGE__SNAPSHOT_PATH: "/qdrant/snapshots"
              QDRANT__TELEMETRY__DISABLE: "true"
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            ports:
              - name: http
                containerPort: *httpPort
              - name: grpc
                containerPort: *grpcPort
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: *httpPort
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 2Gi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault

    service:
      qdrant:
        ports:
          http:
            port: *httpPort
          grpc:
            port: *grpcPort

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${DOMAIN_5}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: domain-5-subdomain-https
        rules:
          - backendRefs:
              - identifier: qdrant
                port: *httpPort

    serviceMonitor:
      app:
        endpoints:
          - port: http
            path: /metrics
            scheme: http
            bearerTokenSecret:
              name: qdrant-secret
              key: QDRANT__SERVICE__API_KEY

    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /qdrant/storage
            subPath: storage
          - path: /qdrant/snapshots
            subPath: snapshots
