---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: mariadb-operator
      version: 25.10.2
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
      interval: 30m
  values:
    crds:
      enabled: false
    ha:
      enabled: true
      replicas: 3
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi
    metrics:
      enabled: true
    pdb:
      enabled: true
      maxUnavailable: 1
    webhook:
      cert:
        certManager:
          enabled: true
          issuerRef:
            name: mariadb-operator
            kind: Issuer
    certController:
      enabled: false
