---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
components:
  - ../../components/common
resources:
  - ./mosquitto/ks.yaml
  - ./zigbee2mqtt/ks.yaml
  - ./zwavejs2mqtt/ks.yaml
  - ./wyoming-piper/ks.yaml
  - ./wyoming-whisper/ks.yaml
  - ./home-assistant/ks.yaml
