---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unbound-state-owner-release
  labels:
    app.kubernetes.io/name: unbound-state-owner
    app.kubernetes.io/part-of: unbound-xi-game
data:
  # renovate-release: depName=git.r1p.dev/unbound-xi/unbound-state-owner
  STATE_OWNER_VERSION: v0.4.2
  STATE_OWNER_DIGEST: sha256:8b5b1a2561607f9f183cf26bdc1e7407f1b74ea3cf020ea23d3d4162fbf3e286
  STATE_OWNER_CONFIG_REVISION: v0.4.0-development-initial
