---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: api-server
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:

      api-server:
        replicas: 3
        strategy: RollingUpdate
        rollingUpdate:
          maxUnavailable: 0
          maxSurge: 1
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/calamityffxi/api-server
              tag: v0.1.13
            env:
              - name: APP_ENV
                value: "production"
            envFrom:
              - secretRef:
                  name: "api-server-game-server-database-secret"
              - secretRef:
                  name: "api-server-database-secret"
              - secretRef:
                  name: "api-server-config-secret"
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

    defaultPodOptions:
      hostUsers: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      imagePullSecrets:
        - name: api-server-ghcr-secret

    service:
      api-server:
        controller: api-server
        ports:
          http:
            port: &port 8080

    route:
      internal:
        hostnames:
          - "api.${DOMAIN_8}"
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: domain-8-subdomain-https
        rules:
          - backendRefs:
              - identifier: api-server
                port: *port
