---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./grafanadashboard.yaml
  - ./helmrelease.yaml
  - ./dnsendpoint.yaml
  - ./servicemonitor.yaml
  - ./prometheusrule.yaml

configMapGenerator:
  - name: grafana-dashboard-calamityxi-api-server-overview
    files:
      - api-server-overview.json=./resources/api-server-overview.json

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/managed-by: grafana-operator
