---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
components:
  - ../../components/common
resources:
  - ./openwebui/ks.yaml
  - ./qdrant/ks.yaml
  - ./crawl4ai/ks.yaml
