---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tandoor
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tandoor-secret
    template:
      data:
        SECRET_KEY: "{{ .TANDOOR_SECRET_KEY }}"
        DB_ENGINE: django.db.backends.postgresql
        POSTGRES_DB: &dbName tandoor
        POSTGRES_HOST: &dbHost postgres-rw.databases.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_USER: &dbUser "{{ .TANDOOR_POSTGRES_USER }}"
        POSTGRES_PASSWORD: &dbPass "{{ .TANDOOR_POSTGRES_PASS }}"
        # Postgres init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: '{{ .POSTGRES_SUPER_PASS }}'
  dataFrom:
    - extract:
        key: tandoor
    - extract:
        key: cloudnative-pg
