---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
components:
  - ../../components/common
resources:
  - ./openwebui/ks.yaml
  - ./searxng/ks.yaml
  - ./n8n/ks.yaml
