---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: non-cluster-services
components:
  - ../../components/common
resources:
  - ./plex/ks.yaml
  - ./adguard/ks.yaml
