---
apiVersion: v1
kind: ConfigMap
metadata:
  name: uxi-ptr-api-config
data:
  config.toml: |
    [common]
    dev_mode = false
    content_dir = "/content"

    [api]
    public_listen = "0.0.0.0:21014"
    internal_listen = "0.0.0.0:21017"
    gateways = ["play-ptr.${DOMAIN_9}:21014"]
    worlds = [{ id = "unboundxi-ptr", name = "Public Test Realm", open = false }]
