---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: uxi-ptr-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: uxi-ptr-server
      app.kubernetes.io/component: api
  podMetricsEndpoints:
    - port: health
      path: /metrics
      interval: 30s
  podTargetLabels:
    - app.kubernetes.io/component
