---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
spec:
  instances: 3
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:${POSTGRESQL_VERSION}
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: openebs-hostpath
  superuserSecret:
    name: immich-postgres-secret
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-postgres-app-secret
      dataChecksums: true
      postInitSQL:
        - ALTER ROLE immich WITH SUPERUSER;
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
        - CREATE EXTENSION IF NOT EXISTS cube;
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
        - CREATE EXTENSION IF NOT EXISTS pg_trgm;
        - CREATE EXTENSION IF NOT EXISTS unaccent;
        - CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
  postgresql:
    shared_preload_libraries:
      - vchord.so
    parameters:
      max_connections: "100"
      shared_buffers: 256MB
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 2Gi
  monitoring:
    enablePodMonitor: true
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: immich-r2
        serverName: immich-postgres-v1
