---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: unbound-xi-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: unbound-xi-internal-ca
spec:
  ca:
    secretName: unbound-xi-internal-ca
