---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tracearr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tracearr-secret
    template:
      data:
        JWT_SECRET: '{{ .JWT_SECRET }}'
        COOKIE_SECRET: '{{ .COOKIE_SECRET }}'
        BETTER_AUTH_SECRET: '{{ .BETTER_AUTH_SECRET }}'
        ENCRYPTION_KEY: '{{ .ENCRYPTION_KEY }}'
        CLAIM_CODE: '{{ .CLAIM_CODE }}'
        DATABASE_URL: postgres://tracearr:{{ .DB_PASSWORD | urlquery }}@tracearr-postgres:5432/tracearr
  dataFrom:
  - extract:
      key: tracearr
