---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app uxi-postgres
  namespace: &namespace uxi
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: onepassword-store
      namespace: external-secrets
    - name: cloudnative-pg
      namespace: databases
    - name: cloudnative-pg-barman-cloud
      namespace: databases
    - name: openebs
      namespace: openebs-system
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  interval: 1h
  path: ./kubernetes/apps/uxi/postgres/app
  postBuild:
    substitute:
      # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgresql
      POSTGRESQL_VERSION: 18.6-minimal-trixie
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
