---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: calamityxi-connect-server
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: calamityxi-connect-server-secret
    template:
      data:
        CONNECT_DEVICE_HMAC_SECRET: "{{ .CONNECT_DEVICE_HMAC_SECRET }}"
  dataFrom:
    - extract:
        key: calamityxi-connect-server
