---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./calamityxi-cluster.yaml
  - ./world-server-dashboard-configmap.yaml
  - ./world-server-servicemonitor.yaml
  - ./connect-server-servicemonitor.yaml
  - ./search-server-dashboard-configmap.yaml
  - ./search-server-servicemonitor.yaml
  - ./search-worker-servicemonitor.yaml
  - ./search-server-prometheusrule.yaml
  - ./world-server-prometheusrule.yaml
  - ./connect-server-prometheusrule.yaml
