---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./calamityxi-cluster.yaml
  - ./grafanadashboard.yaml
  - ./world-server-servicemonitor.yaml
  - ./connect-server-servicemonitor.yaml
  - ./search-server-servicemonitor.yaml
  - ./search-worker-servicemonitor.yaml
  - ./search-server-prometheusrule.yaml
  - ./world-server-prometheusrule.yaml
  - ./connect-server-prometheusrule.yaml
  - ./operator-prometheusrule.yaml
  - ./map-heartbeat-sidecar-podmonitor.yaml
  - ./map-heartbeat-sidecar-prometheusrule.yaml

configMapGenerator:
  - name: grafana-dashboard-calamityxi-connect-server-overview
    files:
      - connect-server-overview.json=./resources/connect-server-overview.json
  - name: grafana-dashboard-calamityxi-search-server-overview
    files:
      - search-server-overview.json=./resources/search-server-overview.json
  - name: grafana-dashboard-calamityxi-world-server-overview
    files:
      - world-server-overview.json=./resources/world-server-overview.json

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/managed-by: grafana-operator
