---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: map-heartbeat-sidecar
  namespace: calamityxi
  labels:
    app.kubernetes.io/name: map-heartbeat-sidecar
spec:
  namespaceSelector:
    matchNames:
      - calamityxi
  selector:
    matchLabels:
      app.kubernetes.io/component: map
      app.kubernetes.io/instance: cxi
      app.kubernetes.io/name: calamityxi-runtime
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
