---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: calamityxi-traffic-probe
  namespace: calamityxi
  labels:
    app.kubernetes.io/name: calamityxi-traffic-probe
spec:
  namespaceSelector:
    matchNames:
      - calamityxi
  selector:
    matchLabels:
      app.kubernetes.io/instance: cxi
      app.kubernetes.io/component: traffic-probe
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
