---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./grafanadashboard.yaml
  - ./helmrelease.yaml
  - ./prometheusrule.yaml

configMapGenerator:
  - name: grafana-dashboard-unifi-uap
    files:
      - unifi-uap.json=./resources/unifi-uap.json

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/managed-by: grafana-operator
