---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nats
  namespace: go-ffxi
spec:
  interval: 30m
  url: https://nats-io.github.io/k8s/helm/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nats
spec:
  interval: 30m
  chart:
    spec:
      chart: nats
      version: 2.12.1
      sourceRef:
        kind: HelmRepository
        name: nats
      interval: 30m
  values:
  # https://artifacthub.io/packages/helm/nats/nats
  # https://github.com/nats-io/k8s/blob/main/helm/charts/nats/values.yaml
