---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/common
resources:
  - ./kube-prometheus-stack/ks.yaml
  - ./grafana/ks.yaml
  - ./snmp-exporter/ks.yaml
  - ./blackbox-exporter/ks.yaml
  - ./unpoller/ks.yaml
