# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: unbound-xi-game
components:
  - ../../components/common
resources:
  - ./api-server/ks.yaml
  - ./api-server/release.yaml
  - ./postgres/ks.yaml
  - ./state-owner/ks.yaml
  - ./state-owner/release.yaml
patches:
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: not-used
        labels:
          pod-security.kubernetes.io/audit: restricted
          pod-security.kubernetes.io/audit-version: v1.36
          pod-security.kubernetes.io/enforce: restricted
          pod-security.kubernetes.io/enforce-version: v1.36
          pod-security.kubernetes.io/warn: restricted
          pod-security.kubernetes.io/warn-version: v1.36
    target:
      kind: Namespace
      name: not-used
