---
apiVersion: v1
kind: ConfigMap
metadata:
  name: uxi-ptr-state-config
data:
  config.toml: |
    [common]
    dev_mode = false
    content_dir = "/content"

    [state]
    health_listen = "0.0.0.0:21020"

    [bus]
    url = "nats://nats.uxi-nats.svc.cluster.local:4222"
    environment = "ptr"
    username = "ptr"
    password_file = "/secrets/nats/password"
