---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: uxi-ptr-state-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: uxi-ptr-state-postgres
    template:
      data:
        world-url: >-
          postgres://uxi_ptr:{{ .UXI_PTR_POSTGRES_PASS | urlquery | replace "+" "%20" }}@uxi-ptr-postgres-rw.uxi-ptr.svc.cluster.local:5432/uxi_ptr?sslmode=verify-full&sslrootcert=/postgres-ca/ca.crt&options=-csearch_path%3Dworld
  dataFrom:
    - extract:
        key: uxi-ptr-postgres
