---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: website-ghcr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: website-ghcr-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .DOCKER_CONFIG_JSON }}"
  dataFrom:
    - extract:
        key: github-pat-calamityxi-private-images
