---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: website
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:

      website:
        replicas: 3
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/calamityffxi/website
              tag: v0.1.11
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 256Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

    defaultPodOptions:
      hostUsers: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      imagePullSecrets:
        - name: website-ghcr-secret

    service:
      website:
        controller: website
        ports:
          http:
            port: &port 80

    persistence:
      cache:
        type: emptyDir
        globalMounts:
          - path: /var/cache/nginx
      run:
        type: emptyDir
        globalMounts:
          - path: /run

    route:
      internal:
        hostnames:
          - "${DOMAIN_8:=domain.com}"
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: domain-8-root-https
        rules:
          - backendRefs:
              - identifier: website
                port: *port
