---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: calamityxi
components:
  - ../../components/common
resources:
  - ./branding/ks.yaml
  - ./early-access/valkey/ks.yaml
  - ./early-access/mariadb/ks.yaml
  - ./api-server/ks.yaml
  - ./game-server/ks.yaml
  # - ./early-access/game-server/common/ks.yaml
  # - ./early-access/game-server/bootstrap/ks.yaml
  # - ./early-access/game-server/world/ks.yaml
  # - ./early-access/game-server/connect/ks.yaml
  # - ./early-access/game-server/search/ks.yaml
  # - ./early-access/game-server/map/ks.yaml
