---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: calamityxi
components:
  - ../../components/common
resources:
  - ./website/ks.yaml
  - ./valkey/ks.yaml
  - ./early-access/mariadb/ks.yaml
  - ./api-server-mariadb/ks.yaml
  - ./api-server/ks.yaml
  - ./operator/ks.yaml
  - ./game-server/ks.yaml
