---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tracearr-redis
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: tracearr-redis
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: tracearr
    ports:
    - protocol: TCP
      port: 6379
