---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-unifi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: external-dns-unifi-secrets
    creationPolicy: Owner
  data:
  - secretKey: UNIFI_API_KEY
    remoteRef:
      key: unifi
      property: api-key
