---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bug-bounty-staff-admin
  labels:
    app.kubernetes.io/name: bug-bounty-staff-admin
    app.kubernetes.io/part-of: bug-bounty
automountServiceAccountToken: false
imagePullSecrets:
  - name: bug-bounty-registry
