---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unbound-gateway
spec:
  secretName: unbound-gateway-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "gateway.${DOMAIN_9}"
  dnsNames:
    - "gateway.${DOMAIN_9}"
