---
endpoints:
  - name: "${APP}"
    group: "internal"
    url: "https://${GATUS_QUERY_URL}"
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    client:
      dns-resolver: "tcp://10.40.1.1:53"
    conditions:
      - "[STATUS] == ${GATUS_STATUS:=200}"
