---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tailscale-operator-secret
    template:
      data:
        client_id: "{{ .OAUTH_CLIENT_ID }}"
        client_secret: "{{ .OAUTH_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: tailscale-operator
