---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gatus
  namespace: &namespace observability
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/gatus/external
  dependsOn:
    - name: cloudnative-pg-cluster
      namespace: databases
    - name: onepassword-store
      namespace: external-secrets
  interval: 1h
  path: ./kubernetes/apps/observability/gatus/app
  postBuild:
    substituteFrom:
      - kind: Secret
        name: domains-secret
        optional: false
    substitute:
      APP: *app
      GATUS_QUERY_URL: "status.${DOMAIN_7}/health"
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
