---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app unbound-game-server
  namespace: &namespace unbound-xi-game
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
      app.kubernetes.io/part-of: unbound-xi-game
  dependsOn:
    - name: unbound-api
      namespace: *namespace
    - name: unbound-api-secrets
      namespace: *namespace
    - name: unbound-coordinator
      namespace: *namespace
    - name: unbound-state-owner
      namespace: *namespace
    - name: kube-prometheus-stack
      namespace: observability
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: unbound-game-server
      namespace: *namespace
  interval: 1h
  path: ./kubernetes/apps/unbound-xi-game/game-server/app
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: unbound-game-server-release
        optional: false
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: true
