---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unbound-game-server-release
  labels:
    app.kubernetes.io/name: unbound-game-server
    app.kubernetes.io/part-of: unbound-xi-game
data:
  # renovate-release: depName=git.r1p.dev/unbound-xi/unbound-game-server
  GAME_SERVER_VERSION: v0.4.5
  GAME_SERVER_DIGEST: sha256:156bc1e23c2cb66080b76844649b72b30c970949f993ed928c5874b6b7909559
