---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unbound-game-server-release
  labels:
    app.kubernetes.io/name: unbound-game-server
    app.kubernetes.io/part-of: unbound-xi-game
data:
  # renovate-release: depName=git.r1p.dev/unbound-xi/unbound-game-server
  GAME_SERVER_VERSION: v0.4.6
  GAME_SERVER_DIGEST: sha256:9f7447c51675f94ad9660516b31579a2c6f640e1a3f950c71e77ca9697517e59
