---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unbound-game-server-release
  labels:
    app.kubernetes.io/name: unbound-game-server
    app.kubernetes.io/part-of: unbound-xi-game
data:
  # renovate-release: depName=git.r1p.dev/unbound-xi/unbound-game-server
  GAME_SERVER_VERSION: v0.4.2
  GAME_SERVER_DIGEST: sha256:c44971e2e5978beee5c7a4bb5178ca57f7342dc178b398e476994c2b2dc2b38e
