---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docmost
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: docmost-secret
    creationPolicy: Owner
    template:
      data:
        APP_SECRET: "{{ .DOCMOST_APP_SECRET }}"
        SMTP_HOST: "{{ .MAILGUN_HOST }}"
        SMTP_PORT: "{{ .MAILGUN_PORT }}"
        SMTP_USERNAME: "{{ .MAILGUN_USERNAME }}"
        SMTP_PASSWORD: "{{ .MAILGUN_PASSWORD }}"
        DATABASE_URL: "postgresql://{{ .DOCMOST_POSTGRES_USER }}:{{ .DOCMOST_POSTGRES_PASS }}@postgres-rw.databases.svc.cluster.local:5432/docmost?schema=public"
        INIT_POSTGRES_DBNAME: docmost
        INIT_POSTGRES_HOST: postgres-rw.databases.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .DOCMOST_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .DOCMOST_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: docmost
    - extract:
        key: cloudnative-pg
    - extract:
        key: mailgun
