---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-github-webhook
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: flux-github-webhook-secret
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: flux
        property: github-webhook-token
