---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: flux-webhook
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  type: github
  events:
    - ping
    - push
  secretRef:
    name: flux-github-webhook-secret
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: flux-system
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      name: flux-system
