---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mariadb-secret
    template:
      data:
        ROOT_PASSWORD: "{{ .MARIADB_ROOT_PASSWORD }}"
        S3_ACCESS_KEY_ID: "{{ .S3_ACCESS_KEY_ID }}"
        S3_SECRET_ACCESS_KEY: "{{ .S3_SECRET_ACCESS_KEY }}"
        USER_GOFFXI_PASSWORD: "{{ .USER_GOFFXI_PASSWORD }}"
  dataFrom:
    - extract:
        key: go-ffxi-mariadb
