---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: ${APP}
spec:
  policyRef:
    name: ${APP}
  schedule:
    cron: "${KOPIUR_SCHEDULE:=H * * * *}"
    jitter: "${KOPIUR_JITTER:=30m}"
