---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vernemq-auth
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: vernemq-auth-secret
    creationPolicy: Owner
  data:
    - secretKey: DOCKER_VERNEMQ_USER_ADMIN
      remoteRef:
        key: vernemq
        property: admin-password
    - secretKey: DOCKER_VERNEMQ_USER_MQTT
      remoteRef:
        key: vernemq
        property: mqtt-password
