---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app rdt-client
  namespace: &namespace media
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: cert-manager-secrets
      namespace: cert-manager
    - name: volsync
      namespace: volsync-system
  interval: 1h
  path: ./kubernetes/apps/media/rdt-client/app
  postBuild:
    substituteFrom:
      - kind: Secret
        name: domains-secret
        optional: false
    substitute:
      APP: *app
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
