---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unbound-coordinator-release
  labels:
    app.kubernetes.io/name: unbound-coordinator
    app.kubernetes.io/part-of: unbound-xi-game
data:
  # renovate-release: depName=git.r1p.dev/unbound-xi/unbound-coordinator
  COORDINATOR_VERSION: v0.4.2
  COORDINATOR_DIGEST: sha256:e950e209b158cb3ef2285f6ea4f0727beb7d91b01dedc870fedd48e009ac989e
