---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unbound-api-release
  labels:
    app.kubernetes.io/name: unbound-api
    app.kubernetes.io/part-of: unbound-xi-game
data:
  # renovate-release: depName=git.r1p.dev/unbound-xi/unbound-api
  API_VERSION: v0.3.0
  API_DIGEST: sha256:d65dba810868d43254f742d9eb14f55327d04ef97c59bb030398af32ac7f18b6
