---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unbound-api-release
  labels:
    app.kubernetes.io/name: unbound-api
    app.kubernetes.io/part-of: unbound-xi-game
data:
  # renovate-release: depName=git.r1p.dev/unbound-xi/unbound-api
  API_VERSION: v0.4.3
  API_DIGEST: sha256:32fe861f17c86d869f4dea1b851ff4cbb83dc0dd273a78faf23911c14e4cccce
