---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: uxi-ptr-gateway
spec:
  interval: 1h
  timeout: 10m
  path: ./kubernetes/apps/uxi/ptr/gateway/app
  prune: true
  wait: true
  dependsOn:
    - name: uxi-ptr-api
      namespace: uxi-ptr
    - name: uxi-ptr-state
      namespace: uxi-ptr
    - name: cilium-gateway
      namespace: kube-system
    - name: reflector
      namespace: kube-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: uxi-ptr
  postBuild:
    substituteFrom:
      - kind: Secret
        name: domains-secret
        optional: false
