---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:

      valkey:
        type: statefulset
        replicas: 1
        containers:
          app:
            image:
              repository: ghcr.io/valkey-io/valkey
              tag: 9.0.3
            command:
              - valkey-server
            args:
              - /etc/valkey/valkey.conf
            resources:
              requests:
                cpu: 250m
                memory: 256Mi
              limits:
                memory: 1Gi
            probes:
              liveness: &valkeyProbe
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - valkey-cli
                      - ping
                  failureThreshold: 3
                  periodSeconds: 10
                  timeoutSeconds: 2
              readiness: *valkeyProbe
              startup:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - valkey-cli
                      - ping
                  failureThreshold: 30
                  periodSeconds: 5
                  timeoutSeconds: 2
        statefulset:
          volumeClaimTemplates:
            - name: data
              storageClass: ceph-block
              size: 2Gi
              accessMode: ReadWriteOnce
              globalMounts:
                - path: /data

    defaultPodOptions:
      hostUsers: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      valkey:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.50.100.31
        ports:
          http:
            port: 6379

    persistence:
      config:
        type: configMap
        name: valkey-config
        globalMounts:
          - path: /etc/valkey
            readOnly: true
