---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: truenas-exporter
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      truenas-exporter:
        containers:
          app:
            image:
              repository: ghcr.io/supporterino/truenas-graphite-to-prometheus
              tag: v2.1.0
            env:
              TZ: America/New_York
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    defaultPodOptions:
      hostUsers: false

    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.50.100.5
        ports:
          metrics:
            port: 9108
          graphite:
            port: 9109

    serviceMonitor:
      app:
        endpoints:
          - port: metrics
