---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unbound-gateway-release
  labels:
    app.kubernetes.io/name: unbound-gateway
    app.kubernetes.io/part-of: unbound-xi-game
data:
  # renovate-release: depName=git.r1p.dev/unbound-xi/unbound-gateway
  GATEWAY_VERSION: v0.4.5
  GATEWAY_DIGEST: sha256:2dbb9befcccecffa313ce637e9960763641471bf98f5420caf71eaeb5679b890
