---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unbound-gateway-release
  labels:
    app.kubernetes.io/name: unbound-gateway
    app.kubernetes.io/part-of: unbound-xi-game
data:
  # renovate-release: depName=git.r1p.dev/unbound-xi/unbound-gateway
  GATEWAY_VERSION: v0.4.8
  GATEWAY_DIGEST: sha256:91a06734379140f213fdd41f1313fed4f44d6112770bcbd1949a3295fc222785
