---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./objectstore.yaml
  - ./cluster.yaml
  - ./prometheusrule.yaml
  - ./scheduledbackup.yaml
