---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: echo-server-domain-5
  labels:
    dns.homelab/external: "true"
spec:
  endpoints:
  - dnsName: "echo-server.${DOMAIN_5}"
    recordTTL: 60
    recordType: CNAME
    targets:
    - "external.${DOMAIN_5}"
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: echo-server-domain-2
  labels:
    dns.homelab/external: "true"
spec:
  endpoints:
  - dnsName: "echo-server.${DOMAIN_2}"
    recordTTL: 60
    recordType: CNAME
    targets:
    - "external.${DOMAIN_2}"
