apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant-early-access-mariadb-access
spec:
  mariaDbRef:
    name: early-access-mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: early-access-mariadb
  table: "*"
  username: calamityxi-early-access
  grantOption: true
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s
