apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant-calamityxi-early-access-db-access
spec:
  mariaDbRef:
    name: calamityxi-mariadb-early-access
  privileges:
    - "ALL PRIVILEGES"
  database: calamityxi-early-access
  table: "*"
  username: calamityxi-early-access
  grantOption: true
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s
