apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: early-access-mariadb
spec:
  name: calamityxi-early-access
  mariaDbRef:
    name: early-access-mariadb
  passwordSecretKeyRef:
    name: early-access-mariadb-secret
    key: USER_PASSWORD
  maxUserConnections: 1000
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s
