---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-packages
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: ceph-block
