---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitea
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: gitea
      app.kubernetes.io/name: gitea
  endpoints:
    - port: http
      path: /metrics
      authorization:
        type: Bearer
        credentials:
          name: gitea-secret
          key: GITEA_METRICS_TOKEN
