---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: domains
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: domains-secret
    creationPolicy: Owner
  data:
  - secretKey: DOMAIN_1
    remoteRef:
      key: cloudflare
      property: domain-1
  - secretKey: DOMAIN_2
    remoteRef:
      key: cloudflare
      property: domain-2
  - secretKey: DOMAIN_3
    remoteRef:
      key: cloudflare
      property: domain-3
  - secretKey: DOMAIN_4
    remoteRef:
      key: cloudflare
      property: domain-4
  - secretKey: DOMAIN_5
    remoteRef:
      key: cloudflare
      property: domain-5
  - secretKey: DOMAIN_6
    remoteRef:
      key: cloudflare
      property: domain-6
