apiVersion: v1
kind: ConfigMap
metadata:
  name: calamityxi-operator-hook-template
data:
  content: |
    spec:
      serviceAccountName: calamityxi-operator-runners
      containers:
        - name: "$job"
          securityContext:
            runAsUser: 0
            runAsGroup: 0
