---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: woodpecker-registry
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: woodpecker-registry
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: >-
          {"auths":{"{{ .WOODPECKER_REGISTRY }}":{"username":"{{ .WOODPECKER_REGISTRY_USERNAME }}","password":"{{ .WOODPECKER_REGISTRY_TOKEN }}"}}}
  dataFrom:
    - extract:
        key: woodpecker
