---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: woodpecker
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: woodpecker-secret
    template:
      data:
        WOODPECKER_AGENT_SECRET: "{{ .WOODPECKER_AGENT_SECRET }}"
        WOODPECKER_ADMIN: "{{ .WOODPECKER_ADMIN }}"
        WOODPECKER_DATABASE_DATASOURCE: "postgres://woodpecker:{{ .WOODPECKER_POSTGRES_PASS }}@postgres-rw.databases.svc.cluster.local:5432/woodpecker?sslmode=disable"
        WOODPECKER_GITEA_CLIENT: "{{ .WOODPECKER_GITEA_CLIENT }}"
        WOODPECKER_GITEA_SECRET: "{{ .WOODPECKER_GITEA_SECRET }}"
        WOODPECKER_PROMETHEUS_AUTH_TOKEN: "{{ .WOODPECKER_PROMETHEUS_AUTH_TOKEN }}"

        # Shared CloudNativePG database initialization
        INIT_POSTGRES_DBNAME: woodpecker
        INIT_POSTGRES_HOST: postgres-rw.databases.svc.cluster.local
        INIT_POSTGRES_USER: woodpecker
        INIT_POSTGRES_PASS: "{{ .WOODPECKER_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: woodpecker
    - extract:
        key: cloudnative-pg
