# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./dnsendpoint.yaml
  - ./networkpolicy.yaml
  - ./podmonitor.yaml
  - ./prometheusrule.yaml
configMapGenerator:
  - name: unbound-api-config
    files:
      - base.toml=./config/base.toml
      - environment.toml=./config/environment.toml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: unbound-api
    app.kubernetes.io/part-of: unbound-xi-game
