---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: unbound-api
  labels:
    app.kubernetes.io/name: unbound-api
    app.kubernetes.io/part-of: unbound-xi-game
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: unbound-api
      app.kubernetes.io/component: public-api
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 5s
