---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: downflate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: downflate-secret
    template:
      data:
        DOWNFLATE_WEBHOOK_SECRET: "{{ .webhookSecret }}"
        DOWNFLATE_GITHUB_APP_CLIENT_ID: "{{ .githubAppClientId }}"
        DOWNFLATE_GITHUB_APP_PRIVATE_KEY: "{{ .githubAppPrivateKey }}"
  data:
    - secretKey: webhookSecret
      remoteRef:
        key: konflate
        property: WEBHOOK_SECRET
    - secretKey: githubAppClientId
      remoteRef:
        key: alfred-bot
        property: GITHUB_APP_CLIENT_ID
    - secretKey: githubAppPrivateKey
      remoteRef:
        key: alfred-bot
        property: GITHUB_APP_PRIVATE_KEY
        decodingStrategy: Base64
