apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant-api-server-mariadb-access
spec:
  mariaDbRef:
    name: api-server-mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: api-server-mariadb
  table: "*"
  username: calamityxi-api-server
  grantOption: true
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s
