---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-certificate
spec:
  secretName: wildcard-certificate-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${DOMAIN_2}"
  dnsNames:
    - "${DOMAIN_1}"
    - "*.${DOMAIN_1}"
    - "${DOMAIN_2}"
    - "*.${DOMAIN_2}"
    - "${DOMAIN_3}"
    - "*.${DOMAIN_3}"
    - "${DOMAIN_4}"
    - "*.${DOMAIN_4}"
    - "${DOMAIN_5}"
    - "*.${DOMAIN_5}"
    - "${DOMAIN_6}"
    - "*.${DOMAIN_6}"
    - "${DOMAIN_7}"
    - "*.${DOMAIN_7}"
